"""Shared plotting configuration constants for fair_sentence_transformers visualizations."""

from __future__ import annotations

DEFAULT_SUBPLOT_COLUMN_SPACING = 0.35
SUBPLOT_COLUMN_SPACING = 0.1
if SUBPLOT_COLUMN_SPACING <= 0:
    raise ValueError("SUBPLOT_COLUMN_SPACING must be positive.")
SUBPLOT_VERTICAL_SCALE = 1.4

SUBPLOT_FONT_SCALE = 1.2
# SUBPLOT_FONT_SCALE = 1.5
BASE_AXIS_LABEL_FONT_SIZE = 17
BASE_TICK_LABEL_FONT_SIZE = 16
BASE_SUBPLOT_TITLE_FONT_SIZE = 18
LEGEND_LINEWIDTH = 4

POS_LABEL_PAD = 8
PLOT_LINEWIDTH = 4
PLOT_MARKERSIZE = 9
